import Link from "next/link";
import { BookingLink } from "@/components/ConversionPanel";
import { SiteFooter, SiteHeader } from "@/components/SiteShell";
import { locationServices } from "@/lib/location-services";
import { insights } from "@/lib/insights";

const faqs = [
  ["What is the difference between managed IT and co-managed IT?", "Managed IT gives an organization one accountable partner for ongoing technology operations. Co-managed IT complements an internal team with capacity, specialized expertise, and clear shared responsibilities."],
  ["How do we begin evaluating an IT partner?", "Start with the business outcomes, current risks, support needs, and systems that matter most. A productive first conversation should clarify the appropriate next step, not force a one-size-fits-all package."],
  ["Can cybersecurity be part of an ongoing IT relationship?", "Yes. Security should be integrated into support, identity, devices, infrastructure, cloud services, continuity, and regular planning instead of treated as a one-time purchase."],
];

export default function Home() {
  return <main>
    <SiteHeader />
    <section className="hero" id="top"><div className="heroGlow" /><div className="heroContent"><p className="eyebrow">MICHIGAN MANAGED IT SERVICES</p><h1>Technology support built around better business decisions.</h1><p className="heroCopy">Northline helps Michigan organizations strengthen daily IT operations, support employees, manage risk, and make the next technology decision with confidence.</p><div className="actions"><BookingLink label="BOOK A CONVERSATION" /><Link className="button ghost" href="/services/managed-it-michigan/">EXPLORE MANAGED IT</Link></div></div></section>
    <section className="section intro"><div className="sectionLead"><p className="eyebrow orange">TWO WAYS TO WORK TOGETHER</p><h2>One accountable partner. The right level of support.</h2></div><div className="introCopy"><p>Choose a fully managed relationship when you want a team to own day-to-day technology. Choose co-managed IT when an internal team needs added capacity, expertise, or coverage.</p><Link href="/insights/managed-it-vs-co-managed-it/">COMPARE THE MODELS →</Link></div><div className="serviceGrid"><article className="serviceCard"><span className="serviceIcon">▦</span><h3>Managed IT</h3><p>Ongoing support, proactive operations, security, and planning for organizations that want one accountable technology partner.</p><Link href="/services/managed-it-michigan/">LEARN MORE <b>→</b></Link></article><article className="serviceCard"><span className="serviceIcon">⇄</span><h3>Co-Managed IT</h3><p>Shared support, specialist skills, and clear escalation for internal IT teams that need more capability without giving up control.</p><Link href="/services/co-managed-it-michigan/">LEARN MORE <b>→</b></Link></article><article className="serviceCard"><span className="serviceIcon">⌾</span><h3>Cybersecurity</h3><p>Practical risk reduction across people, identities, devices, cloud services, monitoring, and continuity planning.</p><Link href="/services/cybersecurity-michigan/">LEARN MORE <b>→</b></Link></article></div></section>
    <section className="why"><div className="whyImage" aria-hidden="true" /><div className="whyContent"><p className="eyebrow orange">HOW NORTHLINE WORKS</p><h2>Clear ownership. Practical progress.</h2><p>Good technology decisions start with the business. Northline works from your priorities, current environment, risks, and budget—not a standard stack.</p><ul><li><i>✓</i><span><b>Understand first</b><small>Clarify what is working, what is exposed, and what matters next.</small></span></li><li><i>✓</i><span><b>Define ownership</b><small>Make support, escalation, and vendor responsibilities clear.</small></span></li><li><i>✓</i><span><b>Improve deliberately</b><small>Turn risks and recurring issues into a practical roadmap.</small></span></li><li><i>✓</i><span><b>Keep decisions connected</b><small>Review technology choices against business outcomes over time.</small></span></li></ul></div></section>
    <section className="section"><div className="sectionHeader"><div><p className="eyebrow orange">SERVICES</p><h2>Capabilities that support the whole environment.</h2></div><Link href="/locations/michigan/">MICHIGAN SERVICE AREAS →</Link></div><div className="articleGrid">{locationServices.filter((service) => !["managed-it-michigan", "co-managed-it-michigan", "cybersecurity-michigan"].includes(service.slug)).slice(0, 3).map((service) => <article key={service.slug}><p>{service.short.toUpperCase()}</p><h3>{service.name}</h3><p className="articleCopy">{service.intro}</p><Link href={`/services/${service.slug}/`}>EXPLORE SERVICE →</Link></article>)}</div></section>
    <section className="section insights"><div className="sectionHeader"><div><p className="eyebrow orange">PRACTICAL INSIGHTS</p><h2>Guidance for consequential technology decisions.</h2></div><Link href="/insights/">VIEW ALL INSIGHTS →</Link></div><div className="articleGrid">{insights.map((insight) => <article key={insight.slug}><p>{insight.category.toUpperCase()}</p><h3>{insight.title}</h3><p className="articleCopy">{insight.description}</p><Link href={`/insights/${insight.slug}/`}>READ INSIGHT →</Link></article>)}</div></section>
    <section className="section faq"><div><p className="eyebrow orange">COMMON QUESTIONS</p><h2>Useful answers before the first conversation.</h2><p>Northline focuses on clear context, practical tradeoffs, and an appropriate next step.</p></div><div className="faqList">{faqs.map(([question, answer]) => <details className="faqItem" key={question}><summary><h3>{question}</h3><b>+</b></summary><p>{answer}</p></details>)}</div></section>
    <section className="cta"><p className="eyebrow">LET’S TALK</p><h2>Find a useful next step for your technology.</h2><p>Bring the situation you are working through. Northline will help clarify what matters and what to do next.</p><BookingLink className="button light" label="BOOK A CONVERSATION" /></section>
    <SiteFooter />
  </main>;
}
